# Generated by Django 2.2.1 on 2019-05-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.CharField(max_length=10),
        ),
    ]
